src/components/Nav/Nav.stories.tsx, src/scss/components/_nav.scss
Cambié los contenedores de <div> a <nav> y modifiqué los estilos en cuanto a texto y bg-color en active, hover y focus.
=> Navegación

src/components/Modal/Modal.stories.tsx, src/scss/components/_modal.scss
Ajustes acordes a la revisión de estilos del UI Kit.
=> fix: Ajustes de estilos en componente modals

src/components/Modal/Modal.stories.tsx, src/scss/components/_modal.scss
Se ha modificado los estilos del modal según el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/d2792c79-7a7d-444c-af65-474b0a8640a3/specs/)
=> feat: Nuevo modal

src/components/Button/Button.stories.tsx, src/scss/components/_button.scss, src/scss/variables/_colors.scss
Se ha modificado los estilos de los botones.
segun el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/specs/)
=> feat - nuevos botones

src/components/Alert/Alert.stories.scss, src/components/Alert/Alert.stories.tsx, src/scss/components/_alert.scss
Se ha modificado los estilos de las alertas y removido el alerta con el boton "cerrar".
segun el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/6e435327-8087-40a6-90e8-d0b8ab6b1b05/specs/)
=> feat: nuevos alerts

src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/index.tsx, src/scss/components/_pagination.scss
Se ha modificado el funcionamiento del paginado junto a sus estilos.
segun el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/2cf15d7d-0492-4559-82bd-2a5e0b58fe13/)
=> feat: Nuevo paginado

src/scss/components/_list-group.scss, src/scss/components/_nav.scss, src/scss/components/_pagination.scss
=> fix: Correcion de de text decoration

src/components/Footer/footer.scss, src/components/Footer/footer.stories.tsx, src/scss/components/_footer.scss
Se ha modificado el footer segun el [nuevo diseño](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/baffc5da-aa2f-4365-a055-f025ca1426db/specs/).
=> feat: nuevo footer

src/components/Progression/ProgressWithSteps.stories.tsx, src/scss/components/_progression.scss
Se ha agregado el nuevo componente para la barra de progreso siguiendo el [diseño](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/39aa3a58-f4ae-4a43-9a04-3834f0028387/specs/).
=> feat: nueva barra de progreso

src/components/Audio/Audio.stories.tsx, src/components/Audio/AudioCard.stories.tsx, src/components/Audio/ContainerAudio.stories.tsx, src/components/Audio/audio.scss, src/scss/components/_audio.scss, src/scss/obelisco.scss
Se ha agregado el nuevo componente audio siguiendo el [diseño](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/eddf12f9-3eac-4e22-bfde-23f278f4dc8a/specs/).
=> feat: nuevo componente audio

src/components/Table/Table.stories.tsx, src/components/Table/TableActions.stories.tsx
Se agrego la carpeta `Con acciones` en tabla para mostrar las acciones con botones, enlaces o combinadas
=> feat: Se agregan acciones para el componente tabla

src/scss/components/_list-group.scss
Se corrigio los accesos en forma horizontal para mobile
=> fix: Se corrigio la lista de accesos para mobile

src/scss/variables/_colors.scss
=> feat: Se agregan nuevos colores

.storybook/preview.ts, src/components/Tooltip/Tooltip.stories.scss, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/index.tsx, src/components/utils.ts, src/scss/components/_tooltip.scss, src/scss/obelisco.scss
Figma: 
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/9BNEtR6VWye73nPWPNgG4t/UI-KIT---Obelisco?node-id=2332-12566&t=EXxRZGbngwpQ35yb-0
- El ancho en desktop es 18rem y en mobile es de 10rem
Dejo la ficha de Estandares tambien:
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/UomlJbV9f4cowU0JP3urLb/Fichas?node-id=188-812&t=NKHlh5rh7couodXt-0
pd: La forma en la que se muestra puede cambiar, mañana Diseño da la respuesta final
pd: El boton con icono se ve mal por que ese cambio se esta haciendo en otra rama, pero lo dejo aca por las dudas solo hay que reemplazar la clase btn-icon por esto:
```
//Botón con ícono
.btn-icon {
gap: 0.25rem;
i,
span {
font-size: 0.8331rem;
}
&.btn-lg {
i,
span {
font-size: 1.25rem;
}
}
}
```
=> feat: tooltip

src/scss/components/_typography.scss, src/styles/Typography/Typography.stories.tsx
Figma: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/zChICIJehQnAA0vGcbks8g/UI-KIT---Obelisco?node-id=618-8339&t=1ZyP6id0WXHdeJgt-0
=> fix: modificaciones en tipografia

src/scss/components/_alert.scss, src/scss/components/_panel.scss
correccion en panel que afectaba listas de tarjetas
=> fix: correccion en panel

src/components/Modal/Modal.stories.tsx, src/components/Modal/index.tsx, src/scss/components/_modal.scss
Figma:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/SMvqWeTeBRwcK7SvgRnBoD/UI-KIT---Obelisco?node-id=7141%3A18874&mode=dev
Ficha:
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/sHrlwRrmv7DwhHHGjG46Y3/Fichas?node-id=1%3A534&mode=dev
=> fix: modal

src/organisms/Footer/Footer.stories.scss, src/organisms/Footer/Footer.stories.tsx, src/scss/components/_footer.scss
figma: 
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/tLWzOsuijCT3fF4wYkswRs/UI-KIT---Obelisco?type=design&node-id=1022-9649&mode=design&t=m006qdeUiRjUqYBd-0
https://www.figma.com/file/qaPkKkpFdu0vPnkFgsbyYf/02.-Indicadores?type=design&node-id=55-15290&mode=design&t=ekGv4u0Q6YxgNnqq-0
=> fix: footer info

src/organisms/Header/Header.stories.scss, src/organisms/Header/Header.stories.tsx, src/organisms/Header/HeaderMobile.stories.tsx, src/organisms/Header/HeaderWithoutSearch.stories.tsx, src/scss/components/_navbar.scss
En los estilos se quitan ciertas  propiedades que generan que no tenga evento para click el input, ademas que se le da un width demasiado pequeño, quizas es posible incluso hacer que mediante click este pase a verse mas grande o dejarlo por defenco con una medida correcta de buscador y que se entienda siempre, por otro lado el responsive hasta ahora esta bien solo que tendrian que verificar si así deberia verse o si se debe ver de otra forma.
=> fix: prueba de solucion en header buscador en mobile

.storybook/preview-head.html, README.md, src/get-started/GetStarted.stories.tsx, src/organisms/Footer/Footer.stories.tsx, src/scss/components/_footer.scss
UI Kit: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/QEEyCebLcdfZQFADYXpPUC/UI-KIT---Obelisco?node-id=5350%3A14464&mode=dev
=> fix: footer icons y actualizacion de boxicons

.storybook/preview.ts, src/components/Banner/Banner.stories.scss, src/components/Banner/Banner.stories.tsx, src/components/Banner/index.tsx, src/scss/components/_banner.scss, src/scss/obelisco.scss
UI KIT: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/UKpMr44qTCGuB7RDUXHhrs/UI-KIT---Obelisco?type=design&node-id=12300%3A30320&mode=design&t=nk51A4RnyTz6jSN6-1
Ficha: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/7FoMHRfK97umYTJa4NcK5s/Fichas?type=design&node-id=4476%3A22139&mode=design&t=nrPWpNa5LlIvYfLQ-1
=> feat: banner

src/scss/components/_cards.scss, src/scss/components/_list-group.scss
=> fix-1_52_3

src/components/Collapse/Collapse.stories.tsx, src/components/Collapse/index.tsx, src/organisms/Header/Header.stories.tsx, src/organisms/Header/HeaderWithoutSearch.stories.tsx, src/organisms/Header/index.tsx, src/scss/components/_cards.scss, src/scss/components/_dropdown.scss, src/scss/components/_nav.scss, src/scss/components/_navbar.scss
Se inicia el maquetado de la variante del componente colapsable en su version nueva de color blanco. 
Diseño de Figma: 
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/X2SHPXNdNXrDPLq4ERTOHl/UI-KIT---Obelisco?node-id=10911%3A21645&mode=dev
Consultas:
Respuesta de equipo de diseño : Si, tiene borde siempre.
**Fixes:**
- Desplegables: se ajusta line-height y se eliminan !important en box-shadow
- Navegación y pestañas: se ajusta line-height
=> fix: variante colapsable color blanco

README.md, src/get-started/GetStarted.stories.tsx, src/organisms/Footer/Footer.stories.tsx
se añade una nota en el readme que indica que ha iniciado el proceso de migracion de bootstrap 4 a la version 5, ademas de que es necesaro añadir una alerta en la seccion de introduccion en el storybook
=> docs: Se añaden avisos que indican el inicio del proceso de migracion de bootstrap
